pagination:
  per_page: 10
  size: 10
role:
  admin: "admin"
  trainee: "trainee"
pictures:
  upload_dir: "uploads"
  accepted_files: "image/jpeg, image/gif, image/png"
  max_size: 5
  avatar_size: "128"
  avatar_small_size: "24"
logs:
  admin_log_path: "log/admin.log"
  last_ten: 10
questions:
  answer_type:
    single_choice: "single_choice"
    multi_choice: "multi_choice"
    text: "text"
status:
  exam:
    start: "start"
    testing: "testing"
    uncheck: "uncheck"
    checked: "checked"
    inactive: "inactive"
exams:
  default_score: 0
  default_spent_time: 0
  default_correct: false
mailer:
  default_mail: "no-reply@fts.framgia.vn"
